### ISSUE TITLE
Tidak mendapatkan Kode OTP

### ISSUE THREAD

**Issue by tenkuken** [namdevel/ovoid-API#10]
Mengapa saya mendapatkan sms
Klik link verifikasi https://ovo.id/app/login?code=aopsidufaopsdifqw9834faiusdhfaiusdfasdf

Bantuan: 1500696

bagaimana cara mendapatkan kode otp yang 4 digit saja ??

**Comment by bionyxxx** [comment]
iya itu otpnya type : LINK

jadi isi kode otp dg string setelah code=

**Comment by namdevel** [comment]
sudah di jawab sama mas @bionyxxx

**Comment by tenkuken** [comment]
pada example.php
echo $app->OTPVerify('+628XXXXXXXXXX', '<otp_ref_id>', '<otp_code / otp_link_code>');

adakah cara untuk mendapatkan otp_code dibandingkan otp_link_code (string panjang sekali) ??

**Comment by tenkuken** [comment]
kalo login mengunakan device baru dapat otp_link_code ? maksudnya device_idnya baru digenerate kk ?

**Comment by namdevel** [comment]
login pertama kali pada device id baru mendapatkan otp link, nanti setelah itu selama device ID tidak berubah akan mendapatkan otp code 4 digit angka

**Comment by tenkuken** [comment]
Terima kasih buat penjelasannya kk..
