### ISSUE TITLE
OVO Update API

### ISSUE THREAD

**Issue by nuzulr24** [namdevel/ovoid-API#14]
Halo bang @namdevel 
Kenalin bang saya nuzul dan user setia dari repository abang. 

Jadi, mau menginformasikan bila ovo baru aja update api, saya sebelumnya coba mengubah app version dari api yang abang buat karna app version sebelumnya sudah *deprecated*. Update yang sekarang ketika sudah saya ubah dan coba request otp itu responnya itu sudah tidak menggunakan otp code melainkan pakai link verif yang dikirim sama pihak ovo.

Karena saya tidak memiliki cara utk melakukan perbaikan utk update api abang soale ngga bisa MITM 😂

Sekian report dari saya

**Comment by namdevel** [comment]
coba cek ini, barangkali problem nya sama #10

**Comment by nuzulr24** [comment]
Ok bang, terima kasih
