### ISSUE TITLE
Refresh token

### ISSUE THREAD

**Issue by alfianagusnady** [namdevel/ovoid-API#15]
bang @namdevel untuk handle refresh token nya gimana ya? ada cara selain mengulang proses yg ada di  /example/getAuthToken.php ?

**Comment by namdevel** [comment]
nanti coba saya cek dulu, lalu saya buat dokumentasinya

**Comment by namdevel** [comment]
setelah saya cek, untuk mendapatkan auth token, caranya cuma pakai proses yg ada di [getAuthToken.php](https://github.com/namdevel/ovoid-API/blob/master/example/getAuthToken.php)

token tidak akan berubah sebelum login ulang, simpan saja token di DB jika tidak ingin mengulang proses.

**Comment by alfianagusnady** [comment]
baik, terima kasih informasinya bang @namdevel
