### ISSUE TITLE
Mau coba transfer bank tapi dicoba di 5 akun, 1 sukses 4 ngga dengan error invalid parameter

### ISSUE THREAD

**Issue by cvkjm** [namdevel/ovoid-API#17]
{"status":401,"data":[],"message":"Unauthorized!"}

Statusnya ini. Kenapa ya mas?

**Comment by namdevel** [comment]
sertakan kode

**Comment by robintan** [comment]
authentication perlu di redo, token stlh login untuk masing2 nomor itu berbeda
