### ISSUE TITLE
<Rahasia Pribadi>

### ISSUE THREAD

**Issue by derodevil** [namdevel/ovoid-API#2]
gimana caranya unlock `rahasia pribadi `, apakah ada syarat?

**Comment by namdevel** [comment]
mohon maaf, untuk unlockSignature tidak saya publish untuk umum. jika memang banyak yg ingin, nanti akan saya realese berupa PHP extension

**Comment by derodevil** [comment]
dengan senang hati. ditunggu releasenya

**Comment by namdevel** [comment]
sudah
