### ISSUE TITLE
Maintanance

### ISSUE THREAD

**Issue by zhinea** [namdevel/ovoid-API#24]
Halo perkenalkan saya Zidna Fadla, saya lumayan tertarik dengan repositori ini. 

Saya ingin menjadi salah satu collaborator, tetapi saya tidak tau cara mendapatkan request nya / sniff app nya. 

Sudah saya coba menggunakan app sniff httpCanary tetapi hasilnya malahan no response

**Comment by namtxs** [comment]
pakai device apa ?
kalao andro coba pake frida
kalo iOS pake charlesProxy

**Comment by zhinea** [comment]
Terimakasih jawabanya, 
Saya menggunakan android. 

Frida membutuhkan akses root?

**Comment by namtxs** [comment]
yap, bisa pake emulator kalo gapunya rooted android device

[Defeating Android Certificate Pinning with Frida](https://httptoolkit.tech/blog/frida-certificate-pinning/)

**Comment by zhinea** [comment]
Jadi seperti ini? 

Android emulator (rooted) -> install Frida

Atau
Android emulator (non-root) -> Frida on ubuntu

**Comment by namtxs** [comment]
dibaca saja link diatas sudah ada penjelasan dan tutorial nya 🙏
