### ISSUE TITLE
#ask

### ISSUE THREAD

**Issue by ashiapppppppp** [namdevel/ovoid-API#25]
Bang saya mau tambahin fitur tapi kenapa selalu tidak ada response ya?
Bahkan respon error atau gagal pun tidak nampak

public function TokenIDM($time)
    {

        $field = array(
            'time_local' => ''.$time.'',
            'merchant_id' => '3112063',
            'payment_mode' => 'OVO_CASH'
        );
        var_dump($this->headers());
        var_dump(json_encode($field));

        return self::request(self::AGW_API . '/voucher-service/v1/p2m', $field, $this->headers());
    }

![Screenshot_2022_0909_000147](https://user-images.githubusercontent.com/87112186/189182412-aca7aac1-9dcc-4fa7-8a66-2d1c6578b5be.png)

Makasih banyak sebelumnya

**Comment by namtxs** [comment]
Feature apa itu kalo boleh tau

**Comment by ashiapppppppp** [comment]
Itu bang, kalo scan qris sebelah nya ada pembayaran indomaret, nah itu yg mau saya tambahkan

Request :
{"time_local":"2022-08-23T03:09:04+07:00","merchant_id":"3112063","payment_mode":"OVO_CASH"}

Respon
{
  "response_code": "OV00000",
  "response_version": "1",
  "response_message": "Success",
  "data": {
    "payment_mode": "OVO_CASH",
    "voucher": "3267953927",
    "expiry_time": "2022-08-22T20:11:04.50748128Z",
    "expiry_time_local": "2022-08-23T03:11:04+07:00",
    "metadata": {
      "duration_ms": 120000,
      "buffer_ms": 90000,
      "warning_threshold_ms": 30000,
      "voucher_display_type": "numbers"
    }
  }
}

**Comment by ashiapppppppp** [comment]
Maaf bang kepencet close
