### ISSUE TITLE
transfer ovo

### ISSUE THREAD

**Issue by adierwanto** [namdevel/ovoid-API#5]
unlockAndValidateTrxId udah ga bisa kah?

**Comment by namdevel** [comment]
masi bisa pak

**Comment by adierwanto** [comment]
pas transfer ovo. gagal terus ya di  function unlockAndValidateTrxId pdahal param $amount, $trxId, $securityCode dah betul
![image](https://user-images.githubusercontent.com/60045689/120136746-0d5cbc00-c1fd-11eb-8839-13edb664b1f1.png)

**Comment by namdevel** [comment]
pastikan device ID sewaktu login dan tf sama ya pak, kuncinya di device ID tidak boleh rubah2
