### ISSUE TITLE
Login2FA Error:1113

### ISSUE THREAD

**Issue by adierwanto** [namdevel/ovoid-API#6]
Pas Login2FA 

"{"message":"Agar bisa mengakses OVO, Update terlebih dulu aplikasi OVO-mu melalui App Store / Play Store","code":1113}"

deviceId udah diupdate uuid bru padahal

**Comment by cvkjm** [comment]
Sama di saya juga gitu

**Comment by namdevel** [comment]
Nanti kalau senggang saya cek

**Comment by g00m00nry0ng** [comment]
Newbie mohon izin titip sandal. Sama nih, dapet error begitu juga.

**Comment by namdevel** [comment]
sepertinya pihak OVO mulai pelit, berhubung saya juga menggunakan library API ovo ini untuk website saya, saya jadi ragu untuk mempublish kode baru nya

**Comment by g00m00nry0ng** [comment]
Barangkali berkenan, mungkin bisa via japri kalau boleh 😁🙏

**Comment by cvkjm** [comment]
Sama nih..kalo boleh japri aja gan..nanti saya bagi ongkos capeknya lah

**Comment by adierwanto** [comment]
publish dong gannn saya trakteer dehhh 😁

**Comment by skyyynewbies** [comment]
> sepertinya pihak OVO mulai pelit, berhubung saya juga menggunakan library API ovo ini untuk website saya, saya jadi ragu untuk mempublish kode baru nya

ayoo publish kode baru nya kakkkk :'(

**Comment by aryokomar** [comment]
publis update an nya kak

**Comment by cvkjm** [comment]
maaf ini blm bisa lagi ya?

**Comment by namdevel** [comment]
updated
