### ISSUE TITLE
https://agw.heusc.id

### ISSUE THREAD

**Issue by skyyynewbies** [namdevel/ovoid-API#7]
Izin bertanya gan, ini base url api agan?
Untuk segala transaksi ovo yg direquest ke base api agan apakah aman? (yang saya maksud apakah data2 hasil request disimpan?)

**Comment by namdevel** [comment]
insyaallah aman, saya tidak menyimpan data apapun

**Comment by FahrezaMaulanaWisnuWardana** [comment]
halo apakah bisa kontak secara pribadi?
lewat email mungkin

**Comment by namdevel** [comment]
@FahrezaMaulanaWisnuWardana <namdevel [at] heusc.id>

**Comment by gengsmb88** [comment]
Halo gan, sebelumnya di https://apigw01.aws.ovo.id kenapa skrng jadi ke https://agw.heusc.id ya, apakah API agan ini aman dan tdk ngelog data?

**Comment by gengsmb88** [comment]
Setelah saya check seharusnya aman karena heusc.id dipakai hanyan untuk login OTP dan verifikasi

**Comment by dutta07** [comment]
Halo, sebelumnya izin make yaa, terus mau tanya ini bakalan jangka panjang ga ya? misal nanti ada perubahan dari api pusat? 

terimakasih.

**Comment by namdevel** [comment]
monggo mas, jika ada error atau api pusat update, silahkan buat issue aja mas 🙏

**Comment by notyan** [comment]
Hallo gan, izin nanya nih, sebelumnya, ini API nya masih jalan ya gan, lalu ada dokumentasi penggunaan package composer ini gak ya, teimakasih

**Comment by namdevel** [comment]
endpoint back to official

**Comment by bionyxxx** [comment]
> endpoint back to official

buat endpoint heusc mohon jangan di shutdown dulu servicenya gan.. belum sempet migrasi, terimakasih
