### ISSUE TITLE
tidak berhasil mendapatkan transactionHistory 

### ISSUE THREAD

**Issue by gyugie** [namdevel/ovoid-API#9]
hallo bang, mau tanya dong untuk 
$ovo->transactionHistory();
{"status":500,"data":[],"message":"Maaf transaksi anda sedang tidak dapat diproses"}%                                                                                                                                 
terdapat response ini kenapa ya ?

**Comment by namdevel** [comment]
sudah saya fix kak 🙏

**Comment by gyugie** [comment]
> sudah saya fix kak 🙏

maaf bang, response nya skrg seperti ini 
{"data":null,"response_code":"OV00013","response_message":"Anda Tidak Memiliki Akses"}%

**Comment by namdevel** [comment]
Coba cek ini [Bearer](https://github.com/namdevel/ovoid-API/commit/b463be63a99d312fa421c6842d44eee9e8dee120#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26)

**Comment by gyugie** [comment]
> Coba cek ini [Bearer](https://github.com/namdevel/ovoid-API/commit/b463be63a99d312fa421c6842d44eee9e8dee120#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26)

iya saya cek sudah ada Bearer nya. tapi response nya tetap seperti ini
{"data":null,"response_code":"OV00013","response_message":"Anda Tidak Memiliki Akses"}

**Comment by namdevel** [comment]
ternyata butuh headers client-id, sudah saya tambahkan monggo di coba lagi kak

**Comment by gyugie** [comment]
> ternyata butuh headers client-id, sudah saya tambahkan monggo di coba lagi kak

> 

wih mantaaapa kak, works!
untuk ovo ini akan ada kena rate limit juga tidak gak seperti kasus yang saya temuin di gopay [#Gopay Block Rate limited ](https://github.com/namdevel/gopay-api/issues/10#issue-996760999)

**Comment by namdevel** [comment]
kalo untuk rate limit tinggal ganti aja device ID nya, biasanya 1 device id gaboleh multiple phone number

**Comment by gyugie** [comment]
> kalo untuk rate limit tinggal ganti aja device ID nya, biasanya 1 device id gaboleh multiple phone number

bisa kasih tau saya bagian mana nya yang harus di ubah?

**Comment by namdevel** [comment]
kalo di OVO (device id)
kalo di gopay (uniqueId sama session Id)

**Comment by gyugie** [comment]
> kalo di OVO (device id)
> kalo di gopay (uniqueId sama session Id)

oke terima kasih gan works!
